"""Weekly aggregation mode for risk-gate.

Walks merged + closed PRs from the past N days, finds the risk-gate
sticky comment on each, parses the score, and opens / updates a
tracking issue with the aggregated report.

Triggered via `mode: weekly_summary` input (typically on a cron schedule).
"""
from __future__ import annotations

import re
from collections import Counter
from datetime import datetime, timedelta, timezone

import requests

WEEKLY_MARKER = "<!-- ai-risk-gate-weekly -->"
PR_MARKER = "<!-- ai-risk-gate -->"

# Parse "Score: 7/10 (HIGH)" from the sticky comment header
SCORE_RE = re.compile(r"Score:\s*(\d+)/10\s*\(([A-Z]+)\)")
SUMMARY_RE = re.compile(r"\n\*\*([^*\n]+)\*\*", re.MULTILINE)
COST_RE = re.compile(r"Cost:\s*`\$([0-9.]+)`")


def _gh(token: str) -> dict:
    return {
        "Authorization": f"Bearer {token}",
        "Accept": "application/vnd.github+json",
        "X-GitHub-Api-Version": "2022-11-28",
    }


def _list_recent_prs(repo: str, token: str, since: datetime) -> list[dict]:
    """List PRs updated since `since` (closed or open). Paginates."""
    url = f"https://api.github.com/repos/{repo}/pulls"
    params = {"state": "closed", "sort": "updated", "direction": "desc", "per_page": 100}
    out = []
    page = 1
    while page < 10:  # cap at 1000 PRs
        params["page"] = page
        r = requests.get(url, headers=_gh(token), params=params, timeout=20)
        r.raise_for_status()
        batch = r.json()
        if not batch:
            break
        keep = [pr for pr in batch
                if datetime.fromisoformat(pr["updated_at"].replace("Z", "+00:00")) >= since]
        out.extend(keep)
        if len(keep) < len(batch):
            break  # older than `since`, stop paginating
        page += 1
    return out


def _find_score_in_pr(repo: str, pr_num: int, token: str) -> dict | None:
    """Fetch PR comments, find risk-gate sticky comment, parse the score."""
    url = f"https://api.github.com/repos/{repo}/issues/{pr_num}/comments"
    r = requests.get(url, headers=_gh(token), timeout=20)
    if r.status_code != 200:
        return None
    for c in r.json():
        body = c.get("body") or ""
        if PR_MARKER not in body:
            continue
        m = SCORE_RE.search(body)
        if not m:
            continue
        score = int(m.group(1))
        label = m.group(2)
        summary_m = SUMMARY_RE.search(body)
        cost_m = COST_RE.search(body)
        return {
            "score": score,
            "label": label,
            "summary": summary_m.group(1) if summary_m else "",
            "cost": float(cost_m.group(1)) if cost_m else 0.0,
        }
    return None


def _build_report(repo: str, since: datetime, scored: list[dict]) -> str:
    if not scored:
        return f"## Weekly AI Risk Gate Summary\n\n_No PRs scored in the last {(datetime.now(timezone.utc) - since).days} days._\n"

    total = len(scored)
    avg = sum(p["score"] for p in scored) / total
    total_cost = sum(p["cost"] for p in scored)

    # Distribution
    dist = Counter(p["label"] for p in scored)

    # High-risk PRs (≥7)
    high_risk = sorted([p for p in scored if p["score"] >= 7],
                       key=lambda p: -p["score"])

    days = (datetime.now(timezone.utc) - since).days
    lines = [
        WEEKLY_MARKER,
        f"## 📊 AI Risk Gate — Last {days}-day summary",
        "",
        f"**Window**: {since.date()} → {datetime.now(timezone.utc).date()}",
        f"**Repo**: `{repo}`",
        "",
        f"### Stats",
        f"- **PRs scored**: {total}",
        f"- **Average score**: {avg:.1f}/10",
        f"- **Total API cost**: ${total_cost:.4f}",
        "",
        f"### Distribution",
    ]
    for label in ["CRITICAL", "HIGH", "MEDIUM", "LOW"]:
        if dist.get(label, 0) > 0:
            emoji = {"CRITICAL": "🔴", "HIGH": "🟠", "MEDIUM": "🟡", "LOW": "🟢"}[label]
            pct = dist[label] / total * 100
            bar = "█" * int(pct / 5)
            lines.append(f"- {emoji} **{label}**: {dist[label]} ({pct:.0f}%) `{bar}`")

    if high_risk:
        lines += ["", f"### ⚠️ High-risk PRs ({len(high_risk)})", ""]
        for p in high_risk[:10]:
            lines.append(f"- **#{p['number']}** ({p['score']}/10 {p['label']}) — "
                         f"[{p['title']}]({p['url']})")
            if p['summary']:
                lines.append(f"  > {p['summary']}")
        if len(high_risk) > 10:
            lines.append(f"- _... and {len(high_risk) - 10} more_")

    lines += [
        "",
        "---",
        f"<sub>Auto-generated by [risk-gate](https://github.com/justinhsu1477/risk-gate) "
        f"in `weekly_summary` mode · {datetime.now(timezone.utc).isoformat(timespec='minutes')}</sub>",
    ]
    return "\n".join(lines)


def _upsert_issue(repo: str, token: str, body: str) -> int:
    """Find existing weekly summary issue (by marker), update; else create."""
    headers = _gh(token)
    # search for existing
    url = f"https://api.github.com/repos/{repo}/issues"
    r = requests.get(url, headers=headers,
                     params={"state": "open", "labels": "risk-gate-weekly", "per_page": 100},
                     timeout=20)
    r.raise_for_status()
    existing_num = None
    for issue in r.json():
        if WEEKLY_MARKER in (issue.get("body") or ""):
            existing_num = issue["number"]
            break

    title = f"[Risk Gate] Weekly summary — {datetime.now(timezone.utc).date()}"

    if existing_num:
        # update
        r = requests.patch(
            f"https://api.github.com/repos/{repo}/issues/{existing_num}",
            headers=headers,
            json={"title": title, "body": body},
            timeout=20,
        )
        r.raise_for_status()
        return existing_num

    # create with label
    # ensure label exists (best-effort)
    requests.post(
        f"https://api.github.com/repos/{repo}/labels",
        headers=headers,
        json={"name": "risk-gate-weekly", "color": "8b5cf6",
              "description": "Auto-generated weekly risk summary"},
        timeout=20,
    )  # ignore 422 already-exists
    r = requests.post(
        url, headers=headers,
        json={"title": title, "body": body, "labels": ["risk-gate-weekly"]},
        timeout=20,
    )
    r.raise_for_status()
    return r.json()["number"]


def run_weekly_summary(*, gh_token: str, repo: str, days: int = 7) -> int:
    if not gh_token or not repo:
        print("[weekly_summary] ERROR: github_token + GITHUB_REPOSITORY required")
        return 2

    since = datetime.now(timezone.utc) - timedelta(days=days)
    print(f"[weekly_summary] Scanning {repo} PRs updated since {since.isoformat()}")

    prs = _list_recent_prs(repo, gh_token, since)
    print(f"[weekly_summary] Found {len(prs)} PRs in window")

    scored = []
    for pr in prs:
        info = _find_score_in_pr(repo, pr["number"], gh_token)
        if info:
            info["number"] = pr["number"]
            info["title"] = pr["title"]
            info["url"] = pr["html_url"]
            scored.append(info)

    print(f"[weekly_summary] {len(scored)} of those had a risk-gate score")

    body = _build_report(repo, since, scored)
    issue_num = _upsert_issue(repo, gh_token, body)
    print(f"[weekly_summary] Wrote to issue #{issue_num}")
    return 0
